INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (165, 100, 'Chicken fillet', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (112, 100, 'Turkey fillet', 'Protein'); 
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (72, 100, 'Hake', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (129, 100, 'Rice', 'carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (157, 100, 'Macaroni', 'carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (378, 100, 'Cereals Corn Flakes', 'carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (884, 100, 'Olive Oil', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (590, 100, 'Almonds', 'Fats');

INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (190, 100, 'Ham', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (157, 100, 'Spaghetti', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (688, 100, 'Walnuts', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (250, 100, 'Chopped Veal', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (389, 100, 'Oatmeal', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (600, 100, 'Pistachios', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (96, 100, 'Anchovy', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (270, 100, 'Bread', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (301, 100, 'Camembert', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (338, 100, 'Chikpeas', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (650, 100, 'Butter', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (130, 100, 'Rabbit', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (12, 100, 'Courgette', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (747, 100, 'Margarine', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (73, 100, 'Clam', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (24, 100, 'Onion', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (374, 100, 'Parmesan Cheese', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (82, 100, 'Sea Bass', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (85, 100, 'Banana', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (891, 100, 'Animal Fat', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (130, 100, 'Chicken thigh', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (26, 100, 'Grapefruit', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (381, 100, 'Cheddar Cheese', 'Fats');


INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (158, 100, 'Tuna', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (122, 100, 'Tod', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (124, 100, 'Sardine', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (96, 100, 'Trout', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (156, 100, 'Eggs', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (288, 100, 'Duck', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (98, 100, 'Lamb', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (57, 100, 'Octopus', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (264, 100, 'Anguilla', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (80, 100, 'Mere', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (73, 100, 'Sepia', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (82, 100, 'Lobster', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (80, 100, 'Sea Bream', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (176, 100, 'Salmon', 'Protein');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (75, 100, 'Pram', 'Protein');

INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (232, 100, 'Avocado', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (30, 100, 'Raspberry', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (31, 100, 'Mandarin', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (45, 100, 'Apple', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (53, 100, 'Orange', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (55, 100, 'Pineapple', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (38, 100, 'Pear', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (15, 100, 'Watermelon', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (625, 100, 'Hazelnut', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (452, 100, 'Peanut', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (349, 100, 'Chesnut', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (256, 100, 'Date', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (588, 100, 'Pine nut', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (124, 100, 'Garlic', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (16, 100, 'Aubergine', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (31, 100, 'Broccoli', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (31, 100, 'Brussels sprout', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (27, 100, 'Asparagus', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (31, 100, 'Spinach', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (70, 100, 'Pea', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (52, 100, 'Bean', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (19, 100, 'Lettuce', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (80, 100, 'Potato', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (26, 100, 'Leek', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (42, 100, 'Beetroot', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (381, 100, 'Lamb', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (16, 100, 'Tomato', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (37, 100, 'Carrot', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (316, 100, 'French Bean', 'Carbohydrates');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (325, 100, 'Lentil', 'Carbohydrates');

INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (373, 100, 'Barley', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (350, 100, 'Rye', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (321, 100, 'Whole Flour', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (409, 100, 'Biscuit', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (345, 100, 'Flour', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (363, 100, 'Corn', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (230, 100, 'Whole Bread', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (371, 100, 'Semolina', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (363, 100, 'Tapioca', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (900, 100, 'Seed Oil', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (63, 100, 'Milk', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (33, 100, 'Skim Milk', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (61, 100, 'Yogurt', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (337, 100, 'Cream', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (263, 100, 'Brie Cheese', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (306, 100, 'Edam Cheese', 'Fats');
INSERT INTO alimentos (calorias, cantidad, nombre, tipo_Alimentos) VALUES (404, 100, 'Emmental Cheese', 'Fats');